# Generated by Django 4.0.2 on 2022-03-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
