# Generated by Django 4.0.2 on 2022-03-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packster', '0004_remove_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
