# Generated by Django 4.0.2 on 2022-03-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packster', '0007_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
    ]
